# Use the official Python image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file
COPY backend/requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY backend/ .

# Expose the application port (assumed to be 5000 for Flask)
EXPOSE 5000

# Command to run the application
CMD ["flask", "run", "--host=0.0.0.0"]