name: CI

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend  # Change to your backend directory
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend  # Change to your backend directory
          pytest  # Adjust this command if you're using a different testing framework

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push